LIBNAME	= librtos
LIBSRC	= croutine.c queue.c list.c tasks.c
LIBSRC	+= portable/MemMang/heap_1.c portable/MemMang/heap_2.c portable/MemMang/heap_3.c portable/GCC/ATMega162/port.c

INCS	+= -Iinclude
LIB	= 

MCU_TARGET	?= atmega644p
MCU_FREQ	?= 12000000 

OPTIMIZE	?= -Os
DEFS		?= -DF_CPU=$(MCU_FREQ)

include ../Makefile.inc
