# Modified by zhiyb (Yubo Zhi)

TRG	= inttest
SRC	= inttest.c
INCDIRS	= ../inc

PRGER		= usbasp
MCU_TARGET	= atmega162
MCU_FREQ	= 8000000

LIBS	+= -lm

EFUSE	= 0xFF
HFUSE	= 0x9C
LFUSE	= 0xE7

include ../Makefile.defs
