# Modified by zhiyb (Yubo Zhi)

TRG	= inttest
SRC	= inttest.c
INCDIRS	= ../inc

PRGER		= c232hm
MCU_TARGET	= atmega162
MCU_FREQ	= 8000000

LIBS	+= -lm

EFUSE	= 0xFF
HFUSE	= 0xD9
LFUSE	= 0x62

include ../Makefile.defs
